In [1]:
import numpy as np
f = open('input/BLOSUM62.txt', 'r')
score = [line.strip().split() for line in f]
alphabet = score[0]
blosum62 = np.array([i[1:] for i in score[1:]], dtype = 'int')
print alphabet
print blosum62

['A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y', '-']
[[ 4  0 -2 -1 -2  0 -2 -1 -1 -1 -1 -2 -1 -1 -1  1  0  0 -3 -2 -5]
 [ 0  9 -3 -4 -2 -3 -3 -1 -3 -1 -1 -3 -3 -3 -3 -1 -1 -1 -2 -2 -5]
 [-2 -3  6  2 -3 -1 -1 -3 -1 -4 -3  1 -1  0 -2  0 -1 -3 -4 -3 -5]
 [-1 -4  2  5 -3 -2  0 -3  1 -3 -2  0 -1  2  0  0 -1 -2 -3 -2 -5]
 [-2 -2 -3 -3  6 -3 -1  0 -3  0  0 -3 -4 -3 -3 -2 -2 -1  1  3 -5]
 [ 0 -3 -1 -2 -3  6 -2 -4 -2 -4 -3  0 -2 -2 -2  0 -2 -3 -2 -3 -5]
 [-2 -3 -1  0 -1 -2  8 -3 -1 -3 -2  1 -2  0  0 -1 -2 -3 -2  2 -5]
 [-1 -1 -3 -3  0 -4 -3  4 -3  2  1 -3 -3 -3 -3 -2 -1  3 -3 -1 -5]
 [-1 -3 -1  1 -3 -2 -1 -3  5 -2 -1  0 -1  1  2  0 -1 -2 -3 -2 -5]
 [-1 -1 -4 -3  0 -4 -3  2 -2  4  2 -3 -3 -2 -2 -2 -1  1 -2 -1 -5]
 [-1 -1 -3 -2  0 -3 -2  1 -1  2  5 -2 -2  0 -1 -1 -1  1 -1 -1 -5]
 [-2 -3  1  0 -3  0  1 -3  0 -3 -2  6 -2  0  0  1  0 -3 -4 -2 -5]
 [-1 -3 -1 -1 -4 -2 -2 -3 -1 -3 -2 -2  7 -1 -2 -1 -1 -2 -4 -3 -5]
 [-1 -3  0  2 -3 -2  0 -3  1 -2  0  

In [2]:
def globalAlignment(x, y, score):
    """ Calculate global alignment value of sequences x and y using
        dynamic programming.  Return global alignment value. """
    
    D = np.zeros((len(x)+1, len(y)+1), dtype = 'int')
    
    for i in range(1, len(x) + 1):
        D[i,0] = D[i-1,0] + score[alphabet.index(x[i-1]), alphabet.index('-')]
        
    for j in range(1, len(y) + 1):
        D[0,j] = D[0,j-1] + score[alphabet.index('-'), alphabet.index(y[j-1])]
        
    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):
            horz = D[i, j-1] + score[alphabet.index('-'), alphabet.index(y[j-1])]
            vert = D[i-1, j] + score[alphabet.index(x[i-1]), alphabet.index('-')]
            diag = D[i-1, j-1] + score[alphabet.index(x[i-1]), alphabet.index(y[j-1])]
            D[i,j] = max(horz, vert, diag)
    return D, D[-1][-1]

In [4]:
D, max_score = globalAlignment('PLEASANTLY','MEASNLY', blosum62)
print (D)
print (max_score)

[[  0  -5 -10 -15 -20 -25 -30 -35]
 [ -5  -2  -6 -11 -16 -21 -26 -31]
 [-10  -3  -5  -7 -12 -17 -17 -22]
 [-15  -8   2  -3  -7 -12 -17 -19]
 [-20 -13  -3   6   1  -4  -9 -14]
 [-25 -18  -8   1  10   5   0  -5]
 [-30 -23 -13  -4   5   8   4  -1]
 [-35 -28 -18  -9   0  11   6   2]
 [-40 -33 -23 -14  -5   6  10   5]
 [-45 -38 -28 -19 -10   1  10   9]
 [-50 -43 -33 -24 -15  -4   5  17]]
17


In [9]:
def fromSource(x, y, score):
    """Find the score from the source (0,0) to each node in the middle column"""
    D = np.zeros((len(x)+1, len(y)/2 +1), dtype = 'int')
    
    for i in range(1, len(x) + 1):
        D[i,0] = D[i-1,0] + score[alphabet.index(x[i-1]), alphabet.index('-')]
        
    for j in range(1, len(y)/2 + 1):
        D[0,j] = D[0,j-1] + score[alphabet.index('-'), alphabet.index(y[j-1])]
        
    for i in range(1, len(x)+1):
        for j in range(1, len(y)/2 +1):
            horz = D[i, j-1] + score[alphabet.index('-'), alphabet.index(y[j-1])]
            vert = D[i-1, j] + score[alphabet.index(x[i-1]), alphabet.index('-')]
            diag = D[i-1, j-1] + score[alphabet.index(x[i-1]), alphabet.index(y[j-1])]
            D[i,j] = max(horz, vert, diag)
    return D   

In [15]:
x,y = 'PLEASANTLY','MEASNLY'
sourceToMiddle = fromSource(x, y, blosum62)
print (sourceToMiddle)
print (sourceToMiddle[:,len(y)/2])

[[  0  -5 -10 -15]
 [ -5  -2  -6 -11]
 [-10  -3  -5  -7]
 [-15  -8   2  -3]
 [-20 -13  -3   6]
 [-25 -18  -8   1]
 [-30 -23 -13  -4]
 [-35 -28 -18  -9]
 [-40 -33 -23 -14]
 [-45 -38 -28 -19]
 [-50 -43 -33 -24]]
[-15 -11  -7  -3   6   1  -4  -9 -14 -19 -24]


In [39]:
def fromSink(x, y, score):
    """Find the score from the sink to each node in the middle column by travelling backwards"""
    x, y = x[::-1],y[::-1]
    D = np.zeros((len(x)+1, (len(y) - len(y)/2) +1), dtype = 'int')
    for i in range(1, len(x) + 1):
        D[i,0] = D[i-1,0] + score[alphabet.index(x[i-1]), alphabet.index('-')]
        
    for j in range(1, (len(y) - len(y)/2) + 1):
        D[0,j] = D[0,j-1] + score[alphabet.index('-'), alphabet.index(y[j-1])]
        
    for i in range(1, len(x)+1):
        for j in range(1, (len(y) - len(y)/2) + 1):
            horz = D[i, j-1] + score[alphabet.index('-'), alphabet.index(y[j-1])]
            vert = D[i-1, j] + score[alphabet.index(x[i-1]), alphabet.index('-')]
            diag = D[i-1, j-1] + score[alphabet.index(x[i-1]), alphabet.index(y[j-1])]
            D[i,j] = max(horz, vert, diag)
    return D   

In [42]:
x,y = 'PLEASANTLY','MEASNLY'
sinkToMiddle = fromSink(x, y, blosum62)
print (sinkToMiddle)
print (sinkToMiddle[:,(len(y) - len(y)/2)][::-1])

[[  0  -5 -10 -15 -20]
 [ -5   7   2  -3  -8]
 [-10   2  11   6   1]
 [-15  -3   6  11   7]
 [-20  -8   1  12  12]
 [-25 -13  -4   7  13]
 [-30 -18  -9   2  11]
 [-35 -23 -14  -3   6]
 [-40 -28 -19  -8   1]
 [-45 -33 -24 -13  -4]
 [-50 -38 -29 -18  -9]]
[ -9  -4   1   6  11  13  12   7   1  -8 -20]


In [76]:
def middleEdge(x, y, score):
    # Find middle node
    sourceToMiddle = fromSource(x, y, score)
    sinkToMiddle = fromSink(x, y, score)
    length = sourceToMiddle[:,len(y)/2] + sinkToMiddle[:,(len(y) - len(y)/2)][::-1]
    i = length.argmax()
    j = len(y)/2
    # Find middle edge
    a, b = len(x)-i, len(y)-j #Middle node in sinkToMiddle 2D array
    # Find which node led to a, b
    horz = sinkToMiddle[a, b-1] + score[alphabet.index('-'), alphabet.index(y[::-1][b-1])]
    vert = sinkToMiddle[a-1, b] + score[alphabet.index(x[::-1][a-1]), alphabet.index('-')]
    diag = sinkToMiddle[a-1, b-1] + score[alphabet.index(x[::-1][a-1]), alphabet.index(y[::-1][b-1])]
    #  Find which node led into the middle node when you did the backwards search from the sink.
    if diag >= vert and diag >= horz:
        k,l = len(x) -(a-1), len(y) - (b-1)
    elif vert >= horz:
        k,l = len(x) -(a-1), len(y) - b
    else:
        k,l = len(x) - a, len(y) - (b-1)
    return (i,j), (k,l)

In [78]:
x,y = 'PLEASANTLY','MEASNLY'
middleEdge(x, y, blosum62)

((4, 3), (5, 4))

In [80]:
x, y = [i.strip() for i in open('input/rosalind_ba5k.txt', 'r')]
middleEdge(x, y, blosum62)

((514, 520), (515, 521))